### PR TITLE
Fix dts transform for imports with both default and named imports

### PR DESCRIPTION
**Pull request by hayes**

### CODE REVIEW

**Review by ije — APPROVED** [review]
great fix to me! thanks~

**Comment by hayes** [comment]
Thanks for the quick review/merge.

When this gets deployed to global cdn will it invalidate the existing cache, or will this only apply to newly built packages?

**Comment by ije** [comment]
new deployment purges the CDN cache automatically, will let you know after deploying

**Comment by hayes** [comment]
Thanks!

**Pull request merged**
