### PR TITLE
Feature Allowlist in config

### PR DESCRIPTION
**Pull request by olekenneth**
This will add support for adding config option for allowed packages and multiple scopes. This is extremely helpful for self-hosted version where you don't want someone looping over every package on npm and ddos your server.

This will:
- add support for multiple scope, not just one
- allow package names
- allow something, ban something
- add tests

### CODE REVIEW

**Comment by olekenneth** [comment]
I guess I need approval before the tests will run again

**Comment by olekenneth** [comment]
Need more context to why this feature is wanted/needed?

**Comment by olekenneth** [comment]
@renhiyama @ije Can you help me to get closer to merge?

**Review by ije — APPROVED** [review]
LGTM, thanks @olekenneth

**Comment by ije** [comment]
hi @olekenneth can you please check the CI failed? thanks

**Comment by olekenneth** [comment]
Yes. Of course. I'll look at it an hour or so

**Comment by ije** [comment]
@olekenneth thanks

**Pull request merged**
